// <auto-generated />
using System;
using MediTrack.TreatmentService.API.TreatmentManagement.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediTrack.TreatmentService.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509235158_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Aggregates.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TechnicalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.DoseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("dose_schedules", (string)null);
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FrequencyHour")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StockAlertThre")
                        .HasColumnType("int");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.MedicationCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Synonyms")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("medication_catalog", (string)null);
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.DoseSchedule", b =>
                {
                    b.HasOne("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.Medication", "Medication")
                        .WithMany("DoseSchedules")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.Medication", b =>
                {
                    b.HasOne("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.MedicationCatalog", "MedicationCatalog")
                        .WithMany("Medications")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Aggregates.Prescription", "Prescription")
                        .WithMany("Medications")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicationCatalog");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Aggregates.Prescription", b =>
                {
                    b.Navigation("Medications");
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.Medication", b =>
                {
                    b.Navigation("DoseSchedules");
                });

            modelBuilder.Entity("MediTrack.TreatmentService.API.TreatmentManagement.Domain.Model.Entities.MedicationCatalog", b =>
                {
                    b.Navigation("Medications");
                });
#pragma warning restore 612, 618
        }
    }
}
